from __future__ import annotations

import difflib
import re
import subprocess
import sys
from pathlib import Path

from sqlglot import exp, parse_one

from .models import CommandResult, Finding


class UnsafePatch(RuntimeError):
    """Raised when the proposed change is broader than the proven repair."""


def build_regression_test(
    workspace: Path,
    finding: Finding,
    table_name: str,
) -> Path:
    tests_dir = workspace / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    test_path = tests_dir / "test_datahub_schema_contract.py"
    body = f'''# Generated by DataLineage Fix Agent.
# DataHub source: {finding.source_urn}
# DataHub downstream: {finding.affected_entity_urn}
import sqlite3
import unittest
from pathlib import Path


class DataHubSchemaContractRegression(unittest.TestCase):
    def test_customer_revenue_query_matches_datahub_schema(self):
        connection = sqlite3.connect(":memory:")
        connection.execute(
            "CREATE TABLE {table_name} ("
            "order_id INTEGER, {finding.replacement_field} INTEGER, "
            "total_amount REAL, order_ts TEXT)"
        )
        connection.executemany(
            "INSERT INTO {table_name} VALUES (?, ?, ?, ?)",
            [
                (1, 101, 12.5, "2026-07-14T10:00:00Z"),
                (2, 101, 7.0, "2026-07-15T10:00:00Z"),
                (3, 202, 5.0, "2026-07-15T11:00:00Z"),
            ],
        )
        query = (Path(__file__).parents[1] / "pipeline/customer_revenue.sql").read_text()
        rows = connection.execute(query).fetchall()
        self.assertEqual(rows, [(101, 19.5), (202, 5.0)])


if __name__ == "__main__":
    unittest.main()
'''
    test_path.write_text(body, encoding="utf-8")
    return test_path


def run_regression(workspace: Path) -> CommandResult:
    command = [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"]
    completed = subprocess.run(
        command,
        cwd=workspace,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    return CommandResult(command=command, returncode=completed.returncode, output=completed.stdout)


def apply_minimal_identifier_patch(sql_path: Path, finding: Finding) -> str:
    before = sql_path.read_text(encoding="utf-8")
    before_tree = parse_one(before, read="sqlite")
    references = [
        node for node in before_tree.find_all(exp.Column) if node.name == finding.missing_field
    ]
    if len(references) != finding.reference_count or not references:
        raise UnsafePatch("SQL references changed after planning; refusing a stale patch")

    pattern = re.compile(rf"(?<![A-Za-z0-9_]){re.escape(finding.missing_field)}(?![A-Za-z0-9_])")
    after, replacements = pattern.subn(finding.replacement_field, before)
    if replacements != finding.reference_count:
        raise UnsafePatch(
            f"Expected {finding.reference_count} identifier replacements, got {replacements}"
        )

    after_tree = parse_one(after, read="sqlite")
    remaining = [
        node for node in after_tree.find_all(exp.Column) if node.name == finding.missing_field
    ]
    if remaining:
        raise UnsafePatch("Old field remains after patch")

    sql_path.write_text(after, encoding="utf-8")
    return "".join(
        difflib.unified_diff(
            before.splitlines(keepends=True),
            after.splitlines(keepends=True),
            fromfile=f"a/{finding.repository_file}",
            tofile=f"b/{finding.repository_file}",
        )
    )
