# Generated by DataLineage Fix Agent.
# DataHub source: urn:li:dataset:(urn:li:dataPlatform:postgres,ecommerce.raw.orders,PROD)
# DataHub downstream: urn:li:dataset:(urn:li:dataPlatform:postgres,analytics.mart_customer_revenue,PROD)
import sqlite3
import unittest
from pathlib import Path


class DataHubSchemaContractRegression(unittest.TestCase):
    def test_customer_revenue_query_matches_datahub_schema(self):
        connection = sqlite3.connect(":memory:")
        connection.execute(
            "CREATE TABLE orders ("
            "order_id INTEGER, customer_key INTEGER, "
            "total_amount REAL, order_ts TEXT)"
        )
        connection.executemany(
            "INSERT INTO orders VALUES (?, ?, ?, ?)",
            [
                (1, 101, 12.5, "2026-07-14T10:00:00Z"),
                (2, 101, 7.0, "2026-07-15T10:00:00Z"),
                (3, 202, 5.0, "2026-07-15T11:00:00Z"),
            ],
        )
        query = (Path(__file__).parents[1] / "pipeline/customer_revenue.sql").read_text()
        rows = connection.execute(query).fetchall()
        self.assertEqual(rows, [(101, 19.5), (202, 5.0)])


if __name__ == "__main__":
    unittest.main()
